---

# hosts configuration

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_host: localhost
      ansible_user: andre
      ansible_become: true
    portal:
      ansible_user: root
      ansible_host: homebox.space
