---

- name: Install the required packages
  apt:
    name: python-pip
    state: present

- name: Install the required packages
  pip:
    name: python-jenkins
    state: present

- name: Create all Jenkins jobs
  include_tasks:
    file: 'create-job.yml'
  loop: '{{ jobs }}'
  loop_control:
    loop_var: job
