---


- name: Update the packages
  register: packages_cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade the distribution
  when: packages_cache.changed
  apt:
    upgrade: true
