---

# Build the portal from scratch
- name: Install the required packages locally
  hosts: localhost
  become: true
  roles:
    - role: local-setup

- name: Build the Homebox portal web site
  hosts: portal
  vars_files:
     - '{{ playbook_dir }}/../config/system.yml'
  roles:
    - role: system-prepare
      tags: system
    - role: docker-install
      tags: docker
    - role: jenkins-install
      tags: jenkins
    - role: jenkins-plugins
      tags: jenkins,plugins
    - role: jenkins-jobs
      tags: jenkins,jobs
