---

# Build the portal from scratch

- name: Build the Homebox portal web site
  hosts: portal
  vars_files:
     - '{{ playbook_dir }}/../config/system.yml'
  roles:
    - role: system-prepare
      tags: system
    - role: docker-install
      tags: docker
