---

- name: Add Docker repository
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    filename: docker

- name: Install Docker packages
  apt:
    name: [ docker-ce, docker-ce-cli, docker-compose ]
    state: latest
